### ISSUE TITLE
Apear 404 while listening

### ISSUE THREAD

**Issue by DvDxx** [AlynxZhou/hikaru#1]
I followed these tutorials
`hikaru` and `hikaru-theme-aria`

when i input `hikaru i hikaru-site` or any other command, it won't exit until I use `Ctrl + C`  to stop the command.

When hikaru is listening on http 
```
LOG: Hikaru is listening on http://localhost:2333/...
LOG: 404: /
(node:4260) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'docPath' of undefined
    at Server.http.createServer (C:\Users\DvD\AppData\Roaming\npm\node_modules\hikaru-coffee\lib\router.js:361:47)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:652:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)

(node:4260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
LOG: 404: /
(node:4260) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'docPath' of undefined
    at Server.http.createServer (C:\Users\DvD\AppData\Roaming\npm\node_modules\hikaru-coffee\lib\router.js:361:47)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:652:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)

(node:4260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Operate under win10

**Comment by AlynxZhou** [comment]
Have you created `srcs/index.md` by yourself? Actually Hikaru only convert files in `srcs/` to `docs/`, so if you don't create it, Hikaru won't create it either.

You'd better start with a `index.md` file with following contents:

```markdown
---
title: index
layout: index
---
```

**Comment by DvDxx** [comment]
It works with other problems after creating `srcs/index.md`.

hikaru site became
![image](https://user-images.githubusercontent.com/33486198/48670278-11012980-eb50-11e8-8401-963f656a370b.png)


I have not modified `themes/aria/config.yml`

```
<div class="social-link sidebar-item">
  <div><i class="far fa-address-card"></i>Social Links</p></div>
  <ul>
	<li>&lt;i class=&quot;fas fa-envelope&quot;&gt;&lt;/i&gt;<a href="mailto:youremail@youremailhost" target="_blank">E-Mail</a></li>
	
	<li>&lt;i class=&quot;fab fa-github&quot;&gt;&lt;/i&gt;<a href="https://github.com/" target="_blank">GitHub</a></li>
	
	<li>&lt;i class=&quot;fab fa-weibo&quot;&gt;&lt;/i&gt;<a href="https://weibo.com/" target="_blank">Weibo</a></li>
  </ul>
</div>
```

**Comment by AlynxZhou** [comment]
@DvDxx please give me your site's `config.yml`, did you set `autoescape: true` for nunjucks? You should set  false, or it will escape your HTML.

**Comment by DvDxx** [comment]
Thanks，it's working properly now.
`autoescape:` defualt setting is true.

**Comment by AlynxZhou** [comment]
Don't know your version of Hikaru but I think I set the default value to false.
